### ISSUE TITLE
Please consider support 'Long Column Header' or 'Super Headline'

### ISSUE THREAD

**Issue by timiil** [el/canvas-table#13]
Hi, great project.

In some usage context, we need to show a quite long text as a table headline,  something like below:

```
| here is a very long column header   |
| -------    | ---------  | --------- |
| Snow       | Falling    | just play |
| Frost      | Sparkling  | cat       |
| Ice        | Cold       | winnter   |
```

or just a super headline is OK too:

```
| here is a very long super header    |
|  Item      | Action     |SomeOne    |
| -------    | ---------  | --------- |
| Snow       | Falling    | just play |
| Frost      | Sparkling  | cat       |
| Ice        | Cold       | winnter   |
```

**Comment by el** [comment]
Hello, why dont you use title or the subtitle for this?

**Comment by timiil** [comment]
sorry about that, i can not find title or subtitle sample code ...

**Comment by el** [comment]
You can see it in the tests:
https://github.com/el/canvas-table/blob/master/test/configuration.spec.ts#L37

**Comment by timiil** [comment]
> You can see it in the tests: https://github.com/el/canvas-table/blob/master/test/configuration.spec.ts#L37

oh, yes, it is work :) very nice!

by the way, how to hidden the column header ? i had pass all columns caption empty string, but still have some height on the column header region . 

thanks you so much !

**Comment by el** [comment]
There is no way to hide the headers right now, but you can pass the header style same as the cell style and use the first row in the columns to make it look like it doesnt have headers.

**Comment by el** [comment]
Here is a sample:
```ts
  const data: CTData = [
    ["Centro comercial Moctezuma", "Francisco Chang", "$200", "Mexico"],
    ["Ernst Handel", "Roland Mendel", "$1400", "Austria"],
    ["Island Trading", "Helen Bennett", "$600", "UK"],
    ["Laughing Bacchus Winecellars", "Yoshi Tannamuri", "$800", "Canada"],
    ["Magazzini Alimentari Riuniti", "Giovanni Rovelli", "$100", "Italy"]
  ];
  const columns: CTColumn[] = [
    { title: "Alfreds Futterkiste" },
    { title: "Maria Anders" },
    { title: "$400", options: { textAlign: "right" } },
    { title: "Germany" }
  ];
  const options: CTOptions = {
    header: {
      fontWeight: "normal",
      color: "#333"
    },
    borders: {
      header: undefined,
      table: { color: "#aaa", width: 1 }
    },
    fit: true,
    title: {
      text: "Expense Report"
    }
  };
```

![image](https://user-images.githubusercontent.com/1488164/160605356-47337ab8-a5b1-45f6-89bd-82319e7689bc.png)

**Comment by timiil** [comment]
thanks so much lady.
