### ISSUE TITLE
ES5 help

### ISSUE THREAD

**Issue by jasperchua99** [el/canvas-table#15]
Uncaught Exception: Error: Cannot find module 'node_modules\canvas-table\dist\index.js'. Please verify that the package.json has a valid "main" entry

**Comment by el** [comment]
Sorry about this, I think there was an issue with the previous build. please try it again with 0.2.1

**Comment by jasperchua99** [comment]
tks but theres new problems after the update,
![image](https://user-images.githubusercontent.com/30612883/170813676-7b4bd48f-8124-4f68-b8b2-cd0cb26bddcd.png)

**Comment by el** [comment]
This looks related to your options. Ensure the number of columns matches the number of data cells in each row.

**Comment by jasperchua99** [comment]
Np, and how can i remove the title from the table? cos right now 0.2.1 i cant do this 
![image](https://user-images.githubusercontent.com/30612883/171009569-bf4b6308-7013-4fe3-9b0a-8126bdeb00ee.png)

**Comment by el** [comment]
What title? Do you mean the header row?
Take a look at this workaround:
https://github.com/el/canvas-table/issues/13#issuecomment-1081775229
