### ISSUE TITLE
Disable header

### ISSUE THREAD

**Issue by rzseattle** [el/canvas-table#16]
Hi. Amazing lib :) 

I got a request about header enabling and disabling. Now there is no way to disable the header and it's problematic when I  don't want to show any header. 

Simple skip first row of data iteration when headerDisabled flag is true would do the job.

**Comment by el** [comment]
I am going to add this feature in the next version, but for now, you can use this workaround:
https://github.com/el/canvas-table/issues/13#issuecomment-1081776793

**Comment by el** [comment]
This feature is now available in the latest version

https://github.com/el/canvas-table/commit/92071930fcd999e3b6af2ce0de54f3917f7bcff1
